# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import talon_one
from talon_one.models.trigger_webhook_block import TriggerWebhookBlock  # noqa: E501
from talon_one.rest import ApiException

class TestTriggerWebhookBlock(unittest.TestCase):
    """TriggerWebhookBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TriggerWebhookBlock
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = talon_one.models.trigger_webhook_block.TriggerWebhookBlock()  # noqa: E501
        if include_optional :
            return TriggerWebhookBlock(
                id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890', 
                type = '0', 
                tags = [
                    '0'
                    ], 
                webhook = talon_one.models.trigger_webhook_block_webhook.TriggerWebhookBlock_webhook(
                    id = 1, 
                    title = 'Thank you for your order.', ), 
                params = {"order_id":"ORD-10293"}, 
                on_error = {
                    'key' : [
                        talon_one.models.block.Block()
                        ]
                    }
            )
        else :
            return TriggerWebhookBlock(
                type = '0',
                webhook = talon_one.models.trigger_webhook_block_webhook.TriggerWebhookBlock_webhook(
                    id = 1, 
                    title = 'Thank you for your order.', ),
        )

    def testTriggerWebhookBlock(self):
        """Test TriggerWebhookBlock"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
