# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerSession](https://docs.talon.one/integration-api/#operation/updateCustomerSessionV2) endpoint is `https://mycompany.talon.one/v2/customer_sessions/{Id}`   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class CampaignPrioritiesChangedNotification(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'application': 'Application',
        'old_priorities': 'dict(str, list[int])',
        'priorities': 'dict(str, list[int])'
    }

    attribute_map = {
        'application': 'application',
        'old_priorities': 'oldPriorities',
        'priorities': 'priorities'
    }

    def __init__(self, application=None, old_priorities=None, priorities=None, local_vars_configuration=None):  # noqa: E501
        """CampaignPrioritiesChangedNotification - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._application = None
        self._old_priorities = None
        self._priorities = None
        self.discriminator = None

        self.application = application
        if old_priorities is not None:
            self.old_priorities = old_priorities
        self.priorities = priorities

    @property
    def application(self):
        """Gets the application of this CampaignPrioritiesChangedNotification.  # noqa: E501


        :return: The application of this CampaignPrioritiesChangedNotification.  # noqa: E501
        :rtype: Application
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this CampaignPrioritiesChangedNotification.


        :param application: The application of this CampaignPrioritiesChangedNotification.  # noqa: E501
        :type: Application
        """
        if self.local_vars_configuration.client_side_validation and application is None:  # noqa: E501
            raise ValueError("Invalid value for `application`, must not be `None`")  # noqa: E501

        self._application = application

    @property
    def old_priorities(self):
        """Gets the old_priorities of this CampaignPrioritiesChangedNotification.  # noqa: E501

        Campaign IDs for each priority. The priority can be one of: ['universal', 'stackable', 'exclusive']   # noqa: E501

        :return: The old_priorities of this CampaignPrioritiesChangedNotification.  # noqa: E501
        :rtype: dict(str, list[int])
        """
        return self._old_priorities

    @old_priorities.setter
    def old_priorities(self, old_priorities):
        """Sets the old_priorities of this CampaignPrioritiesChangedNotification.

        Campaign IDs for each priority. The priority can be one of: ['universal', 'stackable', 'exclusive']   # noqa: E501

        :param old_priorities: The old_priorities of this CampaignPrioritiesChangedNotification.  # noqa: E501
        :type: dict(str, list[int])
        """

        self._old_priorities = old_priorities

    @property
    def priorities(self):
        """Gets the priorities of this CampaignPrioritiesChangedNotification.  # noqa: E501

        Campaign IDs for each priority. The priority can be one of: ['universal', 'stackable', 'exclusive']   # noqa: E501

        :return: The priorities of this CampaignPrioritiesChangedNotification.  # noqa: E501
        :rtype: dict(str, list[int])
        """
        return self._priorities

    @priorities.setter
    def priorities(self, priorities):
        """Sets the priorities of this CampaignPrioritiesChangedNotification.

        Campaign IDs for each priority. The priority can be one of: ['universal', 'stackable', 'exclusive']   # noqa: E501

        :param priorities: The priorities of this CampaignPrioritiesChangedNotification.  # noqa: E501
        :type: dict(str, list[int])
        """
        if self.local_vars_configuration.client_side_validation and priorities is None:  # noqa: E501
            raise ValueError("Invalid value for `priorities`, must not be `None`")  # noqa: E501

        self._priorities = priorities

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CampaignPrioritiesChangedNotification):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CampaignPrioritiesChangedNotification):
            return True

        return self.to_dict() != other.to_dict()
