# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class CustomerReward(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'application_id': 'int',
        'profile_integration_id': 'str',
        'integration_id': 'str',
        'unlocked_at': 'datetime',
        'used_at': 'datetime'
    }

    attribute_map = {
        'application_id': 'applicationId',
        'profile_integration_id': 'profileIntegrationId',
        'integration_id': 'integrationId',
        'unlocked_at': 'unlockedAt',
        'used_at': 'usedAt'
    }

    def __init__(self, application_id=None, profile_integration_id=None, integration_id=None, unlocked_at=None, used_at=None, local_vars_configuration=None):  # noqa: E501
        """CustomerReward - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._application_id = None
        self._profile_integration_id = None
        self._integration_id = None
        self._unlocked_at = None
        self._used_at = None
        self.discriminator = None

        self.application_id = application_id
        self.profile_integration_id = profile_integration_id
        self.integration_id = integration_id
        self.unlocked_at = unlocked_at
        if used_at is not None:
            self.used_at = used_at

    @property
    def application_id(self):
        """Gets the application_id of this CustomerReward.  # noqa: E501

        The ID of the Application in which the reward was unlocked.  # noqa: E501

        :return: The application_id of this CustomerReward.  # noqa: E501
        :rtype: int
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this CustomerReward.

        The ID of the Application in which the reward was unlocked.  # noqa: E501

        :param application_id: The application_id of this CustomerReward.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and application_id is None:  # noqa: E501
            raise ValueError("Invalid value for `application_id`, must not be `None`")  # noqa: E501

        self._application_id = application_id

    @property
    def profile_integration_id(self):
        """Gets the profile_integration_id of this CustomerReward.  # noqa: E501

        The integration ID of the customer profile that unlocked this reward.  # noqa: E501

        :return: The profile_integration_id of this CustomerReward.  # noqa: E501
        :rtype: str
        """
        return self._profile_integration_id

    @profile_integration_id.setter
    def profile_integration_id(self, profile_integration_id):
        """Sets the profile_integration_id of this CustomerReward.

        The integration ID of the customer profile that unlocked this reward.  # noqa: E501

        :param profile_integration_id: The profile_integration_id of this CustomerReward.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and profile_integration_id is None:  # noqa: E501
            raise ValueError("Invalid value for `profile_integration_id`, must not be `None`")  # noqa: E501

        self._profile_integration_id = profile_integration_id

    @property
    def integration_id(self):
        """Gets the integration_id of this CustomerReward.  # noqa: E501

        The integration ID assigned to this reward unlock.  # noqa: E501

        :return: The integration_id of this CustomerReward.  # noqa: E501
        :rtype: str
        """
        return self._integration_id

    @integration_id.setter
    def integration_id(self, integration_id):
        """Sets the integration_id of this CustomerReward.

        The integration ID assigned to this reward unlock.  # noqa: E501

        :param integration_id: The integration_id of this CustomerReward.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and integration_id is None:  # noqa: E501
            raise ValueError("Invalid value for `integration_id`, must not be `None`")  # noqa: E501

        self._integration_id = integration_id

    @property
    def unlocked_at(self):
        """Gets the unlocked_at of this CustomerReward.  # noqa: E501

        The date and time when the reward was unlocked.  # noqa: E501

        :return: The unlocked_at of this CustomerReward.  # noqa: E501
        :rtype: datetime
        """
        return self._unlocked_at

    @unlocked_at.setter
    def unlocked_at(self, unlocked_at):
        """Sets the unlocked_at of this CustomerReward.

        The date and time when the reward was unlocked.  # noqa: E501

        :param unlocked_at: The unlocked_at of this CustomerReward.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and unlocked_at is None:  # noqa: E501
            raise ValueError("Invalid value for `unlocked_at`, must not be `None`")  # noqa: E501

        self._unlocked_at = unlocked_at

    @property
    def used_at(self):
        """Gets the used_at of this CustomerReward.  # noqa: E501

        The date and time when the reward was used.  # noqa: E501

        :return: The used_at of this CustomerReward.  # noqa: E501
        :rtype: datetime
        """
        return self._used_at

    @used_at.setter
    def used_at(self, used_at):
        """Sets the used_at of this CustomerReward.

        The date and time when the reward was used.  # noqa: E501

        :param used_at: The used_at of this CustomerReward.  # noqa: E501
        :type: datetime
        """

        self._used_at = used_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerReward):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CustomerReward):
            return True

        return self.to_dict() != other.to_dict()
