# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class ExpiringCardPointsData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'expiry_date': 'date',
        'loyalty_program_id': 'int',
        'amount_of_expiring_points': 'float',
        'subledger_id': 'str',
        'card_identifier': 'str',
        'users_per_card_limit': 'int',
        'profiles': 'list[str]'
    }

    attribute_map = {
        'expiry_date': 'ExpiryDate',
        'loyalty_program_id': 'LoyaltyProgramID',
        'amount_of_expiring_points': 'AmountOfExpiringPoints',
        'subledger_id': 'SubledgerID',
        'card_identifier': 'CardIdentifier',
        'users_per_card_limit': 'UsersPerCardLimit',
        'profiles': 'Profiles'
    }

    def __init__(self, expiry_date=None, loyalty_program_id=None, amount_of_expiring_points=None, subledger_id=None, card_identifier=None, users_per_card_limit=None, profiles=None, local_vars_configuration=None):  # noqa: E501
        """ExpiringCardPointsData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._expiry_date = None
        self._loyalty_program_id = None
        self._amount_of_expiring_points = None
        self._subledger_id = None
        self._card_identifier = None
        self._users_per_card_limit = None
        self._profiles = None
        self.discriminator = None

        self.expiry_date = expiry_date
        self.loyalty_program_id = loyalty_program_id
        self.amount_of_expiring_points = amount_of_expiring_points
        self.subledger_id = subledger_id
        self.card_identifier = card_identifier
        self.users_per_card_limit = users_per_card_limit
        self.profiles = profiles

    @property
    def expiry_date(self):
        """Gets the expiry_date of this ExpiringCardPointsData.  # noqa: E501

        The expiration date of loyalty points.  # noqa: E501

        :return: The expiry_date of this ExpiringCardPointsData.  # noqa: E501
        :rtype: date
        """
        return self._expiry_date

    @expiry_date.setter
    def expiry_date(self, expiry_date):
        """Sets the expiry_date of this ExpiringCardPointsData.

        The expiration date of loyalty points.  # noqa: E501

        :param expiry_date: The expiry_date of this ExpiringCardPointsData.  # noqa: E501
        :type: date
        """
        if self.local_vars_configuration.client_side_validation and expiry_date is None:  # noqa: E501
            raise ValueError("Invalid value for `expiry_date`, must not be `None`")  # noqa: E501

        self._expiry_date = expiry_date

    @property
    def loyalty_program_id(self):
        """Gets the loyalty_program_id of this ExpiringCardPointsData.  # noqa: E501

        The ID of the loyalty program.  # noqa: E501

        :return: The loyalty_program_id of this ExpiringCardPointsData.  # noqa: E501
        :rtype: int
        """
        return self._loyalty_program_id

    @loyalty_program_id.setter
    def loyalty_program_id(self, loyalty_program_id):
        """Sets the loyalty_program_id of this ExpiringCardPointsData.

        The ID of the loyalty program.  # noqa: E501

        :param loyalty_program_id: The loyalty_program_id of this ExpiringCardPointsData.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and loyalty_program_id is None:  # noqa: E501
            raise ValueError("Invalid value for `loyalty_program_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                loyalty_program_id is not None and loyalty_program_id < 1):  # noqa: E501
            raise ValueError("Invalid value for `loyalty_program_id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._loyalty_program_id = loyalty_program_id

    @property
    def amount_of_expiring_points(self):
        """Gets the amount_of_expiring_points of this ExpiringCardPointsData.  # noqa: E501

        The amount of loyalty points that will be expired soon.  # noqa: E501

        :return: The amount_of_expiring_points of this ExpiringCardPointsData.  # noqa: E501
        :rtype: float
        """
        return self._amount_of_expiring_points

    @amount_of_expiring_points.setter
    def amount_of_expiring_points(self, amount_of_expiring_points):
        """Sets the amount_of_expiring_points of this ExpiringCardPointsData.

        The amount of loyalty points that will be expired soon.  # noqa: E501

        :param amount_of_expiring_points: The amount_of_expiring_points of this ExpiringCardPointsData.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and amount_of_expiring_points is None:  # noqa: E501
            raise ValueError("Invalid value for `amount_of_expiring_points`, must not be `None`")  # noqa: E501

        self._amount_of_expiring_points = amount_of_expiring_points

    @property
    def subledger_id(self):
        """Gets the subledger_id of this ExpiringCardPointsData.  # noqa: E501

        The ID of the subledger within the loyalty program where these points were added.  # noqa: E501

        :return: The subledger_id of this ExpiringCardPointsData.  # noqa: E501
        :rtype: str
        """
        return self._subledger_id

    @subledger_id.setter
    def subledger_id(self, subledger_id):
        """Sets the subledger_id of this ExpiringCardPointsData.

        The ID of the subledger within the loyalty program where these points were added.  # noqa: E501

        :param subledger_id: The subledger_id of this ExpiringCardPointsData.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and subledger_id is None:  # noqa: E501
            raise ValueError("Invalid value for `subledger_id`, must not be `None`")  # noqa: E501

        self._subledger_id = subledger_id

    @property
    def card_identifier(self):
        """Gets the card_identifier of this ExpiringCardPointsData.  # noqa: E501

        The alphanumeric identifier of the loyalty card.  # noqa: E501

        :return: The card_identifier of this ExpiringCardPointsData.  # noqa: E501
        :rtype: str
        """
        return self._card_identifier

    @card_identifier.setter
    def card_identifier(self, card_identifier):
        """Sets the card_identifier of this ExpiringCardPointsData.

        The alphanumeric identifier of the loyalty card.  # noqa: E501

        :param card_identifier: The card_identifier of this ExpiringCardPointsData.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and card_identifier is None:  # noqa: E501
            raise ValueError("Invalid value for `card_identifier`, must not be `None`")  # noqa: E501

        self._card_identifier = card_identifier

    @property
    def users_per_card_limit(self):
        """Gets the users_per_card_limit of this ExpiringCardPointsData.  # noqa: E501

        The maximum number of customer profiles with which a card can be shared. This can be set to `0` for no limit.   # noqa: E501

        :return: The users_per_card_limit of this ExpiringCardPointsData.  # noqa: E501
        :rtype: int
        """
        return self._users_per_card_limit

    @users_per_card_limit.setter
    def users_per_card_limit(self, users_per_card_limit):
        """Sets the users_per_card_limit of this ExpiringCardPointsData.

        The maximum number of customer profiles with which a card can be shared. This can be set to `0` for no limit.   # noqa: E501

        :param users_per_card_limit: The users_per_card_limit of this ExpiringCardPointsData.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and users_per_card_limit is None:  # noqa: E501
            raise ValueError("Invalid value for `users_per_card_limit`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                users_per_card_limit is not None and users_per_card_limit < 0):  # noqa: E501
            raise ValueError("Invalid value for `users_per_card_limit`, must be a value greater than or equal to `0`")  # noqa: E501

        self._users_per_card_limit = users_per_card_limit

    @property
    def profiles(self):
        """Gets the profiles of this ExpiringCardPointsData.  # noqa: E501

        The integration IDs of the customer profiles linked to the card.  # noqa: E501

        :return: The profiles of this ExpiringCardPointsData.  # noqa: E501
        :rtype: list[str]
        """
        return self._profiles

    @profiles.setter
    def profiles(self, profiles):
        """Sets the profiles of this ExpiringCardPointsData.

        The integration IDs of the customer profiles linked to the card.  # noqa: E501

        :param profiles: The profiles of this ExpiringCardPointsData.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and profiles is None:  # noqa: E501
            raise ValueError("Invalid value for `profiles`, must not be `None`")  # noqa: E501

        self._profiles = profiles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExpiringCardPointsData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExpiringCardPointsData):
            return True

        return self.to_dict() != other.to_dict()
