# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'profile_integration_id': 'str',
        'loyalty_program_id': 'int',
        'subledger_id': 'str',
        'source_of_event': 'str',
        'current_tier': 'str',
        'current_points': 'float',
        'old_tier': 'str',
        'tier_expiration_date': 'datetime',
        'timestamp_of_tier_change': 'datetime',
        'published_at': 'datetime'
    }

    attribute_map = {
        'profile_integration_id': 'ProfileIntegrationID',
        'loyalty_program_id': 'LoyaltyProgramID',
        'subledger_id': 'SubledgerID',
        'source_of_event': 'SourceOfEvent',
        'current_tier': 'CurrentTier',
        'current_points': 'CurrentPoints',
        'old_tier': 'OldTier',
        'tier_expiration_date': 'TierExpirationDate',
        'timestamp_of_tier_change': 'TimestampOfTierChange',
        'published_at': 'PublishedAt'
    }

    def __init__(self, profile_integration_id=None, loyalty_program_id=None, subledger_id=None, source_of_event=None, current_tier=None, current_points=None, old_tier=None, tier_expiration_date=None, timestamp_of_tier_change=None, published_at=None, local_vars_configuration=None):  # noqa: E501
        """IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._profile_integration_id = None
        self._loyalty_program_id = None
        self._subledger_id = None
        self._source_of_event = None
        self._current_tier = None
        self._current_points = None
        self._old_tier = None
        self._tier_expiration_date = None
        self._timestamp_of_tier_change = None
        self._published_at = None
        self.discriminator = None

        self.profile_integration_id = profile_integration_id
        self.loyalty_program_id = loyalty_program_id
        self.subledger_id = subledger_id
        self.source_of_event = source_of_event
        if current_tier is not None:
            self.current_tier = current_tier
        self.current_points = current_points
        if old_tier is not None:
            self.old_tier = old_tier
        if tier_expiration_date is not None:
            self.tier_expiration_date = tier_expiration_date
        if timestamp_of_tier_change is not None:
            self.timestamp_of_tier_change = timestamp_of_tier_change
        self.published_at = published_at

    @property
    def profile_integration_id(self):
        """Gets the profile_integration_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The profile_integration_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: str
        """
        return self._profile_integration_id

    @profile_integration_id.setter
    def profile_integration_id(self, profile_integration_id):
        """Sets the profile_integration_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param profile_integration_id: The profile_integration_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and profile_integration_id is None:  # noqa: E501
            raise ValueError("Invalid value for `profile_integration_id`, must not be `None`")  # noqa: E501

        self._profile_integration_id = profile_integration_id

    @property
    def loyalty_program_id(self):
        """Gets the loyalty_program_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The loyalty_program_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: int
        """
        return self._loyalty_program_id

    @loyalty_program_id.setter
    def loyalty_program_id(self, loyalty_program_id):
        """Sets the loyalty_program_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param loyalty_program_id: The loyalty_program_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and loyalty_program_id is None:  # noqa: E501
            raise ValueError("Invalid value for `loyalty_program_id`, must not be `None`")  # noqa: E501

        self._loyalty_program_id = loyalty_program_id

    @property
    def subledger_id(self):
        """Gets the subledger_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The subledger_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: str
        """
        return self._subledger_id

    @subledger_id.setter
    def subledger_id(self, subledger_id):
        """Sets the subledger_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param subledger_id: The subledger_id of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and subledger_id is None:  # noqa: E501
            raise ValueError("Invalid value for `subledger_id`, must not be `None`")  # noqa: E501

        self._subledger_id = subledger_id

    @property
    def source_of_event(self):
        """Gets the source_of_event of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The source_of_event of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: str
        """
        return self._source_of_event

    @source_of_event.setter
    def source_of_event(self, source_of_event):
        """Sets the source_of_event of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param source_of_event: The source_of_event of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and source_of_event is None:  # noqa: E501
            raise ValueError("Invalid value for `source_of_event`, must not be `None`")  # noqa: E501

        self._source_of_event = source_of_event

    @property
    def current_tier(self):
        """Gets the current_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The current_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: str
        """
        return self._current_tier

    @current_tier.setter
    def current_tier(self, current_tier):
        """Sets the current_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param current_tier: The current_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: str
        """

        self._current_tier = current_tier

    @property
    def current_points(self):
        """Gets the current_points of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The current_points of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: float
        """
        return self._current_points

    @current_points.setter
    def current_points(self, current_points):
        """Sets the current_points of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param current_points: The current_points of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and current_points is None:  # noqa: E501
            raise ValueError("Invalid value for `current_points`, must not be `None`")  # noqa: E501

        self._current_points = current_points

    @property
    def old_tier(self):
        """Gets the old_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The old_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: str
        """
        return self._old_tier

    @old_tier.setter
    def old_tier(self, old_tier):
        """Sets the old_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param old_tier: The old_tier of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: str
        """

        self._old_tier = old_tier

    @property
    def tier_expiration_date(self):
        """Gets the tier_expiration_date of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The tier_expiration_date of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: datetime
        """
        return self._tier_expiration_date

    @tier_expiration_date.setter
    def tier_expiration_date(self, tier_expiration_date):
        """Sets the tier_expiration_date of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param tier_expiration_date: The tier_expiration_date of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: datetime
        """

        self._tier_expiration_date = tier_expiration_date

    @property
    def timestamp_of_tier_change(self):
        """Gets the timestamp_of_tier_change of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501


        :return: The timestamp_of_tier_change of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp_of_tier_change

    @timestamp_of_tier_change.setter
    def timestamp_of_tier_change(self, timestamp_of_tier_change):
        """Sets the timestamp_of_tier_change of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.


        :param timestamp_of_tier_change: The timestamp_of_tier_change of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: datetime
        """

        self._timestamp_of_tier_change = timestamp_of_tier_change

    @property
    def published_at(self):
        """Gets the published_at of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501

        Timestamp when the event was published.  # noqa: E501

        :return: The published_at of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :rtype: datetime
        """
        return self._published_at

    @published_at.setter
    def published_at(self, published_at):
        """Sets the published_at of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.

        Timestamp when the event was published.  # noqa: E501

        :param published_at: The published_at of this IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and published_at is None:  # noqa: E501
            raise ValueError("Invalid value for `published_at`, must not be `None`")  # noqa: E501

        self._published_at = published_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IntegrationHubEventPayloadLoyaltyProfileBasedTierDowngradeNotification):
            return True

        return self.to_dict() != other.to_dict()
