# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class MCPOAuthServerMetadata(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'issuer': 'str',
        'authorization_endpoint': 'str',
        'token_endpoint': 'str',
        'registration_endpoint': 'str',
        'response_types_supported': 'list[str]',
        'grant_types_supported': 'list[str]',
        'code_challenge_methods_supported': 'list[str]'
    }

    attribute_map = {
        'issuer': 'issuer',
        'authorization_endpoint': 'authorization_endpoint',
        'token_endpoint': 'token_endpoint',
        'registration_endpoint': 'registration_endpoint',
        'response_types_supported': 'response_types_supported',
        'grant_types_supported': 'grant_types_supported',
        'code_challenge_methods_supported': 'code_challenge_methods_supported'
    }

    def __init__(self, issuer=None, authorization_endpoint=None, token_endpoint=None, registration_endpoint=None, response_types_supported=None, grant_types_supported=None, code_challenge_methods_supported=None, local_vars_configuration=None):  # noqa: E501
        """MCPOAuthServerMetadata - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._issuer = None
        self._authorization_endpoint = None
        self._token_endpoint = None
        self._registration_endpoint = None
        self._response_types_supported = None
        self._grant_types_supported = None
        self._code_challenge_methods_supported = None
        self.discriminator = None

        self.issuer = issuer
        self.authorization_endpoint = authorization_endpoint
        self.token_endpoint = token_endpoint
        self.registration_endpoint = registration_endpoint
        self.response_types_supported = response_types_supported
        self.grant_types_supported = grant_types_supported
        self.code_challenge_methods_supported = code_challenge_methods_supported

    @property
    def issuer(self):
        """Gets the issuer of this MCPOAuthServerMetadata.  # noqa: E501

        The authorization server's issuer identifier (its base URL).  # noqa: E501

        :return: The issuer of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: str
        """
        return self._issuer

    @issuer.setter
    def issuer(self, issuer):
        """Sets the issuer of this MCPOAuthServerMetadata.

        The authorization server's issuer identifier (its base URL).  # noqa: E501

        :param issuer: The issuer of this MCPOAuthServerMetadata.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and issuer is None:  # noqa: E501
            raise ValueError("Invalid value for `issuer`, must not be `None`")  # noqa: E501

        self._issuer = issuer

    @property
    def authorization_endpoint(self):
        """Gets the authorization_endpoint of this MCPOAuthServerMetadata.  # noqa: E501

        URL of the authorization endpoint.  # noqa: E501

        :return: The authorization_endpoint of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: str
        """
        return self._authorization_endpoint

    @authorization_endpoint.setter
    def authorization_endpoint(self, authorization_endpoint):
        """Sets the authorization_endpoint of this MCPOAuthServerMetadata.

        URL of the authorization endpoint.  # noqa: E501

        :param authorization_endpoint: The authorization_endpoint of this MCPOAuthServerMetadata.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and authorization_endpoint is None:  # noqa: E501
            raise ValueError("Invalid value for `authorization_endpoint`, must not be `None`")  # noqa: E501

        self._authorization_endpoint = authorization_endpoint

    @property
    def token_endpoint(self):
        """Gets the token_endpoint of this MCPOAuthServerMetadata.  # noqa: E501

        URL of the token endpoint.  # noqa: E501

        :return: The token_endpoint of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: str
        """
        return self._token_endpoint

    @token_endpoint.setter
    def token_endpoint(self, token_endpoint):
        """Sets the token_endpoint of this MCPOAuthServerMetadata.

        URL of the token endpoint.  # noqa: E501

        :param token_endpoint: The token_endpoint of this MCPOAuthServerMetadata.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and token_endpoint is None:  # noqa: E501
            raise ValueError("Invalid value for `token_endpoint`, must not be `None`")  # noqa: E501

        self._token_endpoint = token_endpoint

    @property
    def registration_endpoint(self):
        """Gets the registration_endpoint of this MCPOAuthServerMetadata.  # noqa: E501

        URL of the client registration endpoint.  # noqa: E501

        :return: The registration_endpoint of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: str
        """
        return self._registration_endpoint

    @registration_endpoint.setter
    def registration_endpoint(self, registration_endpoint):
        """Sets the registration_endpoint of this MCPOAuthServerMetadata.

        URL of the client registration endpoint.  # noqa: E501

        :param registration_endpoint: The registration_endpoint of this MCPOAuthServerMetadata.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and registration_endpoint is None:  # noqa: E501
            raise ValueError("Invalid value for `registration_endpoint`, must not be `None`")  # noqa: E501

        self._registration_endpoint = registration_endpoint

    @property
    def response_types_supported(self):
        """Gets the response_types_supported of this MCPOAuthServerMetadata.  # noqa: E501

        List of supported OAuth2 response types.  # noqa: E501

        :return: The response_types_supported of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: list[str]
        """
        return self._response_types_supported

    @response_types_supported.setter
    def response_types_supported(self, response_types_supported):
        """Sets the response_types_supported of this MCPOAuthServerMetadata.

        List of supported OAuth2 response types.  # noqa: E501

        :param response_types_supported: The response_types_supported of this MCPOAuthServerMetadata.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and response_types_supported is None:  # noqa: E501
            raise ValueError("Invalid value for `response_types_supported`, must not be `None`")  # noqa: E501

        self._response_types_supported = response_types_supported

    @property
    def grant_types_supported(self):
        """Gets the grant_types_supported of this MCPOAuthServerMetadata.  # noqa: E501

        List of supported OAuth2 grant types.  # noqa: E501

        :return: The grant_types_supported of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: list[str]
        """
        return self._grant_types_supported

    @grant_types_supported.setter
    def grant_types_supported(self, grant_types_supported):
        """Sets the grant_types_supported of this MCPOAuthServerMetadata.

        List of supported OAuth2 grant types.  # noqa: E501

        :param grant_types_supported: The grant_types_supported of this MCPOAuthServerMetadata.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and grant_types_supported is None:  # noqa: E501
            raise ValueError("Invalid value for `grant_types_supported`, must not be `None`")  # noqa: E501

        self._grant_types_supported = grant_types_supported

    @property
    def code_challenge_methods_supported(self):
        """Gets the code_challenge_methods_supported of this MCPOAuthServerMetadata.  # noqa: E501

        List of supported PKCE code challenge methods.  # noqa: E501

        :return: The code_challenge_methods_supported of this MCPOAuthServerMetadata.  # noqa: E501
        :rtype: list[str]
        """
        return self._code_challenge_methods_supported

    @code_challenge_methods_supported.setter
    def code_challenge_methods_supported(self, code_challenge_methods_supported):
        """Sets the code_challenge_methods_supported of this MCPOAuthServerMetadata.

        List of supported PKCE code challenge methods.  # noqa: E501

        :param code_challenge_methods_supported: The code_challenge_methods_supported of this MCPOAuthServerMetadata.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and code_challenge_methods_supported is None:  # noqa: E501
            raise ValueError("Invalid value for `code_challenge_methods_supported`, must not be `None`")  # noqa: E501

        self._code_challenge_methods_supported = code_challenge_methods_supported

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MCPOAuthServerMetadata):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MCPOAuthServerMetadata):
            return True

        return self.to_dict() != other.to_dict()
