# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`.   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class MCPOAuthProtectedResource(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'resource': 'str',
        'authorization_servers': 'list[str]'
    }

    attribute_map = {
        'resource': 'resource',
        'authorization_servers': 'authorization_servers'
    }

    def __init__(self, resource=None, authorization_servers=None, local_vars_configuration=None):  # noqa: E501
        """MCPOAuthProtectedResource - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._resource = None
        self._authorization_servers = None
        self.discriminator = None

        self.resource = resource
        self.authorization_servers = authorization_servers

    @property
    def resource(self):
        """Gets the resource of this MCPOAuthProtectedResource.  # noqa: E501

        The URL of the protected resource (the MCP entrypoint).  # noqa: E501

        :return: The resource of this MCPOAuthProtectedResource.  # noqa: E501
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this MCPOAuthProtectedResource.

        The URL of the protected resource (the MCP entrypoint).  # noqa: E501

        :param resource: The resource of this MCPOAuthProtectedResource.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and resource is None:  # noqa: E501
            raise ValueError("Invalid value for `resource`, must not be `None`")  # noqa: E501

        self._resource = resource

    @property
    def authorization_servers(self):
        """Gets the authorization_servers of this MCPOAuthProtectedResource.  # noqa: E501

        List of authorization server base URLs that can issue tokens for this resource.  # noqa: E501

        :return: The authorization_servers of this MCPOAuthProtectedResource.  # noqa: E501
        :rtype: list[str]
        """
        return self._authorization_servers

    @authorization_servers.setter
    def authorization_servers(self, authorization_servers):
        """Sets the authorization_servers of this MCPOAuthProtectedResource.

        List of authorization server base URLs that can issue tokens for this resource.  # noqa: E501

        :param authorization_servers: The authorization_servers of this MCPOAuthProtectedResource.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and authorization_servers is None:  # noqa: E501
            raise ValueError("Invalid value for `authorization_servers`, must not be `None`")  # noqa: E501

        self._authorization_servers = authorization_servers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MCPOAuthProtectedResource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MCPOAuthProtectedResource):
            return True

        return self.to_dict() != other.to_dict()
