# coding: utf-8

"""
    Talon.One API

    Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`   # noqa: E501

    The version of the OpenAPI document: 
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from talon_one.configuration import Configuration


class TierUpgradeData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'customer_profile_id': 'str',
        'loyalty_program_id': 'int',
        'subledger_id': 'str',
        'current_tier': 'str',
        'current_points': 'float',
        'old_tier': 'str',
        'points_required_to_the_next_tier': 'float',
        'next_tier': 'str',
        'tier_expiration_date': 'datetime',
        'timestamp_of_tier_change': 'datetime'
    }

    attribute_map = {
        'customer_profile_id': 'CustomerProfileID',
        'loyalty_program_id': 'LoyaltyProgramID',
        'subledger_id': 'SubledgerID',
        'current_tier': 'CurrentTier',
        'current_points': 'CurrentPoints',
        'old_tier': 'OldTier',
        'points_required_to_the_next_tier': 'PointsRequiredToTheNextTier',
        'next_tier': 'NextTier',
        'tier_expiration_date': 'TierExpirationDate',
        'timestamp_of_tier_change': 'TimestampOfTierChange'
    }

    def __init__(self, customer_profile_id=None, loyalty_program_id=None, subledger_id='', current_tier=None, current_points=None, old_tier=None, points_required_to_the_next_tier=None, next_tier=None, tier_expiration_date=None, timestamp_of_tier_change=None, local_vars_configuration=None):  # noqa: E501
        """TierUpgradeData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._customer_profile_id = None
        self._loyalty_program_id = None
        self._subledger_id = None
        self._current_tier = None
        self._current_points = None
        self._old_tier = None
        self._points_required_to_the_next_tier = None
        self._next_tier = None
        self._tier_expiration_date = None
        self._timestamp_of_tier_change = None
        self.discriminator = None

        self.customer_profile_id = customer_profile_id
        self.loyalty_program_id = loyalty_program_id
        self.subledger_id = subledger_id
        self.current_tier = current_tier
        self.current_points = current_points
        if old_tier is not None:
            self.old_tier = old_tier
        if points_required_to_the_next_tier is not None:
            self.points_required_to_the_next_tier = points_required_to_the_next_tier
        if next_tier is not None:
            self.next_tier = next_tier
        self.tier_expiration_date = tier_expiration_date
        self.timestamp_of_tier_change = timestamp_of_tier_change

    @property
    def customer_profile_id(self):
        """Gets the customer_profile_id of this TierUpgradeData.  # noqa: E501

        The integration ID of the customer profile whose tier was upgraded.  # noqa: E501

        :return: The customer_profile_id of this TierUpgradeData.  # noqa: E501
        :rtype: str
        """
        return self._customer_profile_id

    @customer_profile_id.setter
    def customer_profile_id(self, customer_profile_id):
        """Sets the customer_profile_id of this TierUpgradeData.

        The integration ID of the customer profile whose tier was upgraded.  # noqa: E501

        :param customer_profile_id: The customer_profile_id of this TierUpgradeData.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and customer_profile_id is None:  # noqa: E501
            raise ValueError("Invalid value for `customer_profile_id`, must not be `None`")  # noqa: E501

        self._customer_profile_id = customer_profile_id

    @property
    def loyalty_program_id(self):
        """Gets the loyalty_program_id of this TierUpgradeData.  # noqa: E501

        The ID of the loyalty program.  # noqa: E501

        :return: The loyalty_program_id of this TierUpgradeData.  # noqa: E501
        :rtype: int
        """
        return self._loyalty_program_id

    @loyalty_program_id.setter
    def loyalty_program_id(self, loyalty_program_id):
        """Sets the loyalty_program_id of this TierUpgradeData.

        The ID of the loyalty program.  # noqa: E501

        :param loyalty_program_id: The loyalty_program_id of this TierUpgradeData.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and loyalty_program_id is None:  # noqa: E501
            raise ValueError("Invalid value for `loyalty_program_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                loyalty_program_id is not None and loyalty_program_id < 1):  # noqa: E501
            raise ValueError("Invalid value for `loyalty_program_id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._loyalty_program_id = loyalty_program_id

    @property
    def subledger_id(self):
        """Gets the subledger_id of this TierUpgradeData.  # noqa: E501

        The ID of the subledger, when applicable. If this field is empty, the main ledger is used.  # noqa: E501

        :return: The subledger_id of this TierUpgradeData.  # noqa: E501
        :rtype: str
        """
        return self._subledger_id

    @subledger_id.setter
    def subledger_id(self, subledger_id):
        """Sets the subledger_id of this TierUpgradeData.

        The ID of the subledger, when applicable. If this field is empty, the main ledger is used.  # noqa: E501

        :param subledger_id: The subledger_id of this TierUpgradeData.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and subledger_id is None:  # noqa: E501
            raise ValueError("Invalid value for `subledger_id`, must not be `None`")  # noqa: E501

        self._subledger_id = subledger_id

    @property
    def current_tier(self):
        """Gets the current_tier of this TierUpgradeData.  # noqa: E501

        The name of the customer's current tier.  # noqa: E501

        :return: The current_tier of this TierUpgradeData.  # noqa: E501
        :rtype: str
        """
        return self._current_tier

    @current_tier.setter
    def current_tier(self, current_tier):
        """Sets the current_tier of this TierUpgradeData.

        The name of the customer's current tier.  # noqa: E501

        :param current_tier: The current_tier of this TierUpgradeData.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and current_tier is None:  # noqa: E501
            raise ValueError("Invalid value for `current_tier`, must not be `None`")  # noqa: E501

        self._current_tier = current_tier

    @property
    def current_points(self):
        """Gets the current_points of this TierUpgradeData.  # noqa: E501

        The number of points the customer had at the time of tier upgrade.  # noqa: E501

        :return: The current_points of this TierUpgradeData.  # noqa: E501
        :rtype: float
        """
        return self._current_points

    @current_points.setter
    def current_points(self, current_points):
        """Sets the current_points of this TierUpgradeData.

        The number of points the customer had at the time of tier upgrade.  # noqa: E501

        :param current_points: The current_points of this TierUpgradeData.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and current_points is None:  # noqa: E501
            raise ValueError("Invalid value for `current_points`, must not be `None`")  # noqa: E501

        self._current_points = current_points

    @property
    def old_tier(self):
        """Gets the old_tier of this TierUpgradeData.  # noqa: E501

        The name of the customer's previous tier.  # noqa: E501

        :return: The old_tier of this TierUpgradeData.  # noqa: E501
        :rtype: str
        """
        return self._old_tier

    @old_tier.setter
    def old_tier(self, old_tier):
        """Sets the old_tier of this TierUpgradeData.

        The name of the customer's previous tier.  # noqa: E501

        :param old_tier: The old_tier of this TierUpgradeData.  # noqa: E501
        :type: str
        """

        self._old_tier = old_tier

    @property
    def points_required_to_the_next_tier(self):
        """Gets the points_required_to_the_next_tier of this TierUpgradeData.  # noqa: E501

        The number of points needed for a customer to reach the next tier.  # noqa: E501

        :return: The points_required_to_the_next_tier of this TierUpgradeData.  # noqa: E501
        :rtype: float
        """
        return self._points_required_to_the_next_tier

    @points_required_to_the_next_tier.setter
    def points_required_to_the_next_tier(self, points_required_to_the_next_tier):
        """Sets the points_required_to_the_next_tier of this TierUpgradeData.

        The number of points needed for a customer to reach the next tier.  # noqa: E501

        :param points_required_to_the_next_tier: The points_required_to_the_next_tier of this TierUpgradeData.  # noqa: E501
        :type: float
        """

        self._points_required_to_the_next_tier = points_required_to_the_next_tier

    @property
    def next_tier(self):
        """Gets the next_tier of this TierUpgradeData.  # noqa: E501

        The name of the customer's next tier.  # noqa: E501

        :return: The next_tier of this TierUpgradeData.  # noqa: E501
        :rtype: str
        """
        return self._next_tier

    @next_tier.setter
    def next_tier(self, next_tier):
        """Sets the next_tier of this TierUpgradeData.

        The name of the customer's next tier.  # noqa: E501

        :param next_tier: The next_tier of this TierUpgradeData.  # noqa: E501
        :type: str
        """

        self._next_tier = next_tier

    @property
    def tier_expiration_date(self):
        """Gets the tier_expiration_date of this TierUpgradeData.  # noqa: E501

        The exact date and time the tier expires.  # noqa: E501

        :return: The tier_expiration_date of this TierUpgradeData.  # noqa: E501
        :rtype: datetime
        """
        return self._tier_expiration_date

    @tier_expiration_date.setter
    def tier_expiration_date(self, tier_expiration_date):
        """Sets the tier_expiration_date of this TierUpgradeData.

        The exact date and time the tier expires.  # noqa: E501

        :param tier_expiration_date: The tier_expiration_date of this TierUpgradeData.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and tier_expiration_date is None:  # noqa: E501
            raise ValueError("Invalid value for `tier_expiration_date`, must not be `None`")  # noqa: E501

        self._tier_expiration_date = tier_expiration_date

    @property
    def timestamp_of_tier_change(self):
        """Gets the timestamp_of_tier_change of this TierUpgradeData.  # noqa: E501

        The exact date and time the tier was changed.  # noqa: E501

        :return: The timestamp_of_tier_change of this TierUpgradeData.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp_of_tier_change

    @timestamp_of_tier_change.setter
    def timestamp_of_tier_change(self, timestamp_of_tier_change):
        """Sets the timestamp_of_tier_change of this TierUpgradeData.

        The exact date and time the tier was changed.  # noqa: E501

        :param timestamp_of_tier_change: The timestamp_of_tier_change of this TierUpgradeData.  # noqa: E501
        :type: datetime
        """
        if self.local_vars_configuration.client_side_validation and timestamp_of_tier_change is None:  # noqa: E501
            raise ValueError("Invalid value for `timestamp_of_tier_change`, must not be `None`")  # noqa: E501

        self._timestamp_of_tier_change = timestamp_of_tier_change

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TierUpgradeData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TierUpgradeData):
            return True

        return self.to_dict() != other.to_dict()
